### ISSUE TITLE
Is this needed? @Adhithyan8

### ISSUE THREAD

**Issue by dannyrichy** [the-nihilist-ninja/git-bisect#4]
```
        # TODO: Is this needed? @Adhithyan8
```

https://github.com/the-nihilist-ninja/git-bisect/blob/d84ce10d67d41124e7b4e2f5a3e537ee6a481d73/core/algo.py#L48

**Comment by Adhithyan8** [comment]
Not relevant for us, as long as `a` and `b` are of same shape. We implicitly assume this is true as our permutation is only on two models with the same architecture.
