### ISSUE TITLE
Check if it is passed as function or function name

### ISSUE THREAD

**Issue by dannyrichy** [the-nihilist-ninja/git-bisect#5]
```
    # @Adhithyan8 TODO: Check if it is passed as function or function name
```

https://github.com/the-nihilist-ninja/git-bisect/blob/c76c49e8bcc0609bc4d0ddb9316851afba2ecd99/models/utils.py#L55

**Comment by Adhithyan8** [comment]
Neither, `model.parameters()` is a generator
